server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my?useSSL=false&useUnicode=true&characterEncoding=UTF-8&nullCatalogMeansCurrent=true
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    timeout: 100
  messages:
    basename: i18n/message
    encoding: UTF-8
  profiles:
    active: dev